name: Continuous integration

on:
    push:
        branches: [main, development]
    pull_request:
        branches: [main, development]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.15.x]

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js and Yarn
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install

            - name: Check linting
              run: yarn lint
            
            - name: Run the e2e tests
              run: yarn test:cypress
            
            - name: Run the unit tests
              run: yarn test:jest

            - name: Build
              run: yarn build

